---
- name: deploy latest new train tracker on EC2
  hosts: all
  remote_user: ubuntu
  become_user: ubuntu
  tasks:
    - name: add nodejs apt key
      become: yes
      become_user: root
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: add nodejs 18.x ppa for apt repo
      become: yes
      become_user: root
      apt_repository:
        repo: deb https://deb.nodesource.com/node_18.x focal main
        update_cache: yes

    - name: install nodejs
      become: yes
      become_user: root
      apt:
        name: nodejs
        state: latest

    - name: add python ppa for apt repo
      become: yes
      become_user: root
      apt_repository:
        repo: ppa:deadsnakes/ppa
        update_cache: yes

    - name: install python3.11
      become: yes
      become_user: root
      apt:
        name: python3.11
        state: latest

    - name: install poetry
      shell: curl -sSL https://install.python-poetry.org | python3 -

    - name: get latest github repo
      git:
        repo: https://github.com/transitmatters/new-train-tracker.git
        dest: /home/ubuntu/new-train-tracker
        force: yes
        version: main

    - name: copy systemd service file
      become: yes
      become_user: root
      copy:
        src: systemd.conf
        dest: /etc/systemd/system/new-train-tracker.service

    - name: install nginx
      become: yes
      become_user: root
      apt:
        name: nginx

    - name: copy nginx config file
      become: yes
      become_user: root
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-enabled/default

    - name: copy secrets file
      copy:
        src: ../server/secrets.py
        dest: /home/ubuntu/new-train-tracker/server/secrets.py

    - name: restart nginx
      become: yes
      become_user: root
      systemd:
        name: nginx
        state: restarted
        daemon_reload: yes

    - name: install app dependencies
      shell: npm ci
      args:
        chdir: /home/ubuntu/new-train-tracker
      environment:
        PATH: /home/ubuntu/.local/bin/:{{ ansible_env.PATH }}

    - name: build application with npm
      shell: npm run build
      args:
        chdir: /home/ubuntu/new-train-tracker
      environment:
        PATH: /home/ubuntu/.local/bin/:{{ ansible_env.PATH }}

    - name: restart new train tracker service
      become: yes
      become_user: root
      shell: systemctl restart new-train-tracker
