[tool.poetry]
name = "new-train-tracker"
version = "2.2.0"
description = "New Train Tracker by TransitMattters"
authors = ["TransitMatters Labs Team"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8, <3.11"
flask = "1.1.4"
aiohttp = "3.8.5"
boto3 = "1.26.153"
gunicorn = "20.1.0"
json-api-doc = "0.15.0"
pytz = "2023.3"
MarkupSafe = "2.0.1"
schedule = "1.1.0"


[tool.poetry.dev-dependencies]
black = "20.8b1"
pylint = "2.13.5"
flake8 = "4.0.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
