[tool.poetry]
name = "new-train-tracker"
version = "2.4.0"
description = "New Train Tracker by TransitMattters"
authors = ["TransitMatters Labs Team"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.12"
aiohttp = "3.10.2"
boto3 = "1.34.118"
json-api-doc = "0.15.0"
pytz = "2024.1"
schedule = "1.2.2"
datadog_lambda = "5.94.0"
ddtrace = "2.8.5"


[tool.poetry.dev-dependencies]
pip = ">=23.3"
chalice = "1.31.1"
black = "^24.4.2"
pylint = "3.2.2"
flake8 = "7.0.0"


[tool.black]
line-length = 120
target-version = ['py312']


[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"
