[tool.poetry]
name = "new-train-tracker"
version = "1.0.0"
description = ""
authors = ["TransitMatters Labs Team"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
flask = "1.1.4"
aiohttp = "3.8.1"
boto3 = "1.23.0"
gunicorn = "20.1.0"
psycopg2 = "2.9.3"
json-api-doc = "0.15.0"
pytz = "2022.1"
MarkupSafe = "2.0.1"


[tool.poetry.dev-dependencies]
black = "20.8b1"
pylint = "2.13.5"
flake8 = "4.0.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
